name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Train model
      run: |
        python --version
        pip --version
        pip install -r train_requirements.txt
        dvc pull
        python train.py
      env:
        GH_TOKEN: ${{ github.token }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context : /home/runner/work/mlops_11/mlops_11
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/my-flask-app:latest

    - name: Run Docker container
      run: |
        docker run -d -p 5000:5000 --name my-flask-app ${{ secrets.DOCKER_USERNAME }}/my-flask-app:latest

    - name: Wait for Flask app to start
      run: sleep 20  # Adjust the sleep duration if needed

    - name: Print Docker container logs
      run: docker logs my-flask-app

    - name: Test Flask app    
      run: |
        curl -X POST -H "Content-Type: application/json" -d "{\"median_income\": [5.0, 6.0, 7.0]}" http://127.0.0.1:5000/predict
